// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';


//Enable this line for docker image deployment
let SUPABASE_URL = "__VITE_SUPABASE_URL__";
let SUPABASE_PUBLISHABLE_KEY = "__VITE_SUPABASE_ANON_KEY__";

// enable this line for local development
//SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
//SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Ensure the variables are defined before creating the client
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("Supabase URL or Publishable Key is not defined. Please check your environment variables.");
  throw new Error("Supabase URL or Publishable Key is missing.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

let cachedSupabase: ReturnType<typeof createClient<Database>> | null = null;

export const supabase = (() => {
  if (cachedSupabase) {
    return cachedSupabase;
  }
  cachedSupabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
  return cachedSupabase;
})();